### ISSUE TITLE
Array  of object  getting key insted of index 

### ISSUE THREAD

**Issue by safiresh** [BinaryThumb/change-case-object#1]
Hi Frostney, 
you are did very good library but you missed out small things array object get issue,
 for example 
Input : 
var obj =[{isActive:true,userId:01}];
Expect Ans : 
[{is_active:true,user_id}]
Actual Ans: 
["0":{is_active:true,user_id}]

Please correct me if i telling wrong means :).

Solution : 
file name : index.js
Replace code : 
var changeKeys = function changeKeys(transformer, obj) {
    if (Object.prototype.toString.call(obj) === '[object Array]') {
        var r = [];
        for (var i = 0; i < obj.length; i++) {
            console.log(obj[i]);
            r.push(changeKeys(transformer, obj[i]));
        }
        return r;
    } else if (typeof obj === 'object') {
        var objectKeys = Object.keys(obj);
        return objectKeys.map(function keysMap(key) {
            return transformer(key);
        }).reduce(function keysReducer(object, changedKey, index) {
            var objValue = obj[objectKeys[index]];

```
        var transformedValue = changeKeys(transformer, objValue);
        object[changedKey] = transformedValue;
        return object;
    }, {});
}
else {
    return obj;
}
```

};

**Comment by frostney** [comment]
Hi @safiresh, thank you for reporting this issue.

I've seen you already forked this repository and updated the code in question. Feel free to do a pull request and I'm gonna review and merge it in.

If you we have time would mind updating the tests as well? :smile:

**Comment by safiresh** [comment]
Hi @frostney , 
I will update test as same.
Kindly publish  to NPM with updated code. its really useful for us.

**Comment by safiresh** [comment]
Kindly  check & publish In NPM .Its usefull for us :)

**Comment by frostney** [comment]
Thank you for your contribution.
I'm sorry for the small delay, I noticed that I hadn't hooked up ESLint correctly previously and I corrected that while fixing lint errors.
I also feel that it's a bigger change than just a patch release, so I bumped the minor version as I feel this is more in-line with the SemVer specification.
